---
# tasks file for mariadb_install
- name: Installation de MariaDB
  package:
    name: "{{  item  }}"
    state: latest
  loop:
    - mariadb-server
    - mariadb-common
    - mariadb-client
    - python-mysqldb

- name: Lancement du service en automatique
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Définition du mot de passe root du SGBD
  mysql_user:
    user: root
    password: "{{ mariadb_root_password }}"
    host: localhost

- name: Suppression du user anonyme pour ansible_fqdn
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    state: "absent"

- name: Suppression du user anonyme pour connexion locale
  mysql_user:
    user: ""
    state: "absent"

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "::1"

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "127.0.0.1"

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "localhost"

- name: Secures the MySQL root user for server_hostname domain
  mysql_user:
    user: "root"
    password: "{{ mariadb_root_password }}"
    host: "{{ ansible_fqdn }}"
