- name: Installation de Wordpress avec des serveurs Web et BDD séparés.
  hosts: SVWEB-02-server, SVWEB-03-server
  gather_facts: yes
  become: yes
  remote_user: murmure
  become_user: root
  become_method: sudo


#*****************************************************
# Définition des variables
#*****************************************************
  vars:
    BDD_server_name: "SVWEB-03"
    Web_server_name: "SVWEB-02"
    mariadb_root_password: "rC66H9f4Yx"
    wordpressuser_name: "wordpressuser"
    wordpressuser_password: "Jr8Xs7Vv27"
    wordpress_dbname: "wordpress"

#*****************************************************
# Définition des variables dynamiques
#*****************************************************
  tasks:

    - name: delegate_facts pour le serveur Web
      setup:
      delegate_to: "{{  Web_server_name  }}"
      delegate_facts: True

    - name: delegate_facts pour le serveur de BDD
      setup:
      delegate_to: "{{  BDD_server_name  }}"
      delegate_facts: True


    - name: ip du serveur Web
      set_fact:
        Web_server_ip: "{{  hostvars[Web_server_name].ansible_default_ipv4.address  }}"

    - name: ip du serveur Web
      set_fact:
        BDD_server_ip: "{{  hostvars[BDD_server_name].ansible_default_ipv4.address  }}"

    - debug:
        msg: "Je suis sur le serveur de BDD et l'ip du serveur web est {{  Web_server_ip  }} "
      when:
        - "BDD_server_name in inventory_hostname"

    - debug:
        msg: "Je suis sur le serveur Web et l'ip du serveur de BDD est {{  BDD_server_ip  }} "
      when:
        - "Web_server_name in inventory_hostname"


    - name: FQDN du serveur Web
      set_fact:
        Web_server_fqdn: "{{  hostvars[Web_server_name].ansible_fqdn  }}"


    - debug:
        msg: "Je suis sur le serveur de BDD : l'ip du serveur web est {{  Web_server_ip  }} et son FQDN {{  Web_server_fqdn  }}"
      when:
        - "BDD_server_name in inventory_hostname"
